# Generated by Django 6.0.1 on 2026-01-14 22:14

import apps.main.file_validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the tool or resource', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Detailed description of what this tool does')),
                ('url', models.URLField(help_text='Official URL or link to the tool')),
                ('category', models.CharField(choices=[('Development', 'Development'), ('Design', 'Design'), ('Framework', 'Framework'), ('Database', 'Database'), ('DevOps', 'DevOps'), ('Testing', 'Testing'), ('Security', 'Security'), ('Productivity', 'Productivity'), ('API', 'API'), ('Cloud', 'Cloud'), ('Mobile', 'Mobile'), ('AI/ML', 'AI/ML'), ('Analytics', 'Analytics'), ('Other', 'Other')], help_text='Category this tool belongs to', max_length=100)),
                ('tags', models.JSONField(blank=True, help_text='List of tags for this tool (as JSON array)', null=True)),
                ('is_favorite', models.BooleanField(default=False, help_text='Mark as favorite tool (will appear on home page)')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this tool is visible on the site')),
                ('icon_url', models.URLField(blank=True, help_text='URL to an icon/logo for this tool', null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image/screenshot for this tool', null=True, upload_to='tools/', validators=[apps.main.file_validators.image_validator])),
                ('pricing', models.CharField(blank=True, help_text="Pricing info (e.g., 'Free', '$10/month', 'Freemium')", max_length=50)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Personal rating from 1-5 stars', null=True)),
                ('last_updated', models.DateField(blank=True, help_text='When this tool info was last updated', null=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this tool has been viewed')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ['category', 'title'],
                'indexes': [models.Index(fields=['category', 'title'], name='tools_tool_categor_5f72a3_idx'), models.Index(fields=['is_favorite', '-created_at'], name='tools_tool_is_favo_b11da6_idx'), models.Index(fields=['is_visible', 'category'], name='tools_tool_is_visi_d1b99d_idx')],
            },
        ),
    ]
