# Generated by Django 6.0.1 on 2026-01-14 22:14

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name (2-100 characters)', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(help_text='Valid email address', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('subject', models.CharField(help_text='Message subject (3-200 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('message', models.TextField(help_text='Message content (10-2000 characters)', validators=[django.core.validators.MinLengthValidator(10)])),
                ('preferred_channel', models.CharField(choices=[('email', 'Email'), ('calendly', 'Plan a call'), ('slack', 'Slack / Teams invite')], default='email', help_text='Preferred response channel', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', '-created_at'], name='contact_con_is_read_debe1e_idx'), models.Index(fields=['-created_at'], name='contact_con_created_00b9df_idx'), models.Index(fields=['email', '-created_at'], name='contact_con_email_4f8e99_idx')],
            },
        ),
    ]
