# Generated by Django 6.0.1 on 2026-01-14 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the blog post', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title (auto-generated if left blank)', max_length=250, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Brief description/summary of the post (max 500 characters)', max_length=500, null=True)),
                ('content', models.TextField(blank=True, help_text='Main content of the blog post (supports Markdown)', null=True)),
                ('featured_image_url', models.URLField(blank=True, help_text='URL to a featured image for this post', null=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Upload a featured image for this post', null=True, upload_to='blog/images/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('unlisted', 'Unlisted'), ('scheduled', 'Scheduled')], default='draft', help_text='Publication status of the post', max_length=10)),
                ('tags', models.JSONField(blank=True, help_text='List of tags for this post (as JSON array)', null=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 characters)', max_length=160)),
                ('published_at', models.DateTimeField(blank=True, help_text='When this post was/will be published', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
