# Generated by Django 6.0.1 on 2026-01-14 22:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='AI aracının adı', max_length=100)),
                ('description', models.TextField(help_text='AI aracının kısa açıklaması')),
                ('url', models.URLField(help_text="AI aracının web sitesi URL'si")),
                ('category', models.CharField(choices=[('general', 'Genel Platformlar & Sohbet'), ('visual', 'Görsel & Tasarım'), ('video', 'Video & Animasyon'), ('audio', 'Ses, Müzik & Podcast'), ('text', 'Yazı & İçerik Üretimi'), ('code', 'Kodlama & Geliştirme'), ('research', 'Araştırma & Akademik'), ('productivity', 'Verimlilik & Yardımcı Araçlar'), ('other', 'Diğer')], default='general', help_text='AI aracının kategorisi', max_length=20)),
                ('icon_url', models.URLField(blank=True, help_text="AI aracının ikonu URL'si (opsiyonel)", null=True)),
                ('image', models.ImageField(blank=True, help_text='AI aracının görseli', null=True, upload_to='ai_tools/')),
                ('is_featured', models.BooleanField(default=False, help_text='Öne çıkan araç olarak işaretle')),
                ('is_free', models.BooleanField(default=True, help_text='Ücretsiz mi?')),
                ('rating', models.FloatField(default=0.0, help_text='Kişisel değerlendirme (0-5)')),
                ('tags', models.CharField(blank=True, help_text='Virgülle ayrılmış etiketler (AI, GPT, vs.)', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Sıralama (küçük sayılar önce görünür)')),
                ('is_visible', models.BooleanField(default=True, help_text='Site üzerinde görünür mü?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Tool',
                'verbose_name_plural': 'AI Tools',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('philosophy', 'Felsefe'), ('history', 'Tarih'), ('sociology', 'Sosyoloji'), ('technology', 'Teknoloji'), ('personal', 'Kişisel'), ('other', 'Diğer')], help_text='Blog kategorisi', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Görüntülenecek kategori adı', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Kategori açıklaması')),
                ('color', models.CharField(default='#3B82F6', help_text='Kategori rengi (hex kod)', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Kategori ikonu (CSS class veya emoji)', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Sıralama')),
                ('is_visible', models.BooleanField(default=True, help_text='Site üzerinde görünür mü?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='CybersecurityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kaynak başlığı', max_length=150)),
                ('description', models.TextField(help_text='Kaynağın detaylı açıklaması')),
                ('content', models.TextField(blank=True, help_text='Ana içerik (Markdown destekli)')),
                ('type', models.CharField(choices=[('tool', 'Güvenlik Aracı'), ('threat', 'Tehdit Türü'), ('standard', 'Standart/Framework'), ('practice', 'En İyi Uygulama'), ('news', 'Güncel Haber/Tehdit'), ('tutorial', 'Eğitim/Rehber'), ('certification', 'Sertifikasyon'), ('other', 'Diğer')], default='tool', help_text='Kaynak türü', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Başlangıç'), ('intermediate', 'Orta'), ('advanced', 'İleri'), ('expert', 'Uzman')], default='beginner', help_text='Zorluk seviyesi', max_length=20)),
                ('url', models.URLField(blank=True, help_text="İlgili web sitesi URL'si", null=True)),
                ('image', models.ImageField(blank=True, help_text='Kaynak görseli', null=True, upload_to='cybersecurity/')),
                ('tags', models.CharField(blank=True, help_text='Virgülle ayrılmış etiketler (malware, firewall, vs.)', max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Öne çıkan kaynak olarak işaretle')),
                ('is_urgent', models.BooleanField(default=False, help_text='Acil/güncel tehdit mi?')),
                ('severity_level', models.IntegerField(choices=[(1, 'Düşük'), (2, 'Orta'), (3, 'Yüksek'), (4, 'Kritik')], default=1, help_text='Önem/ciddiyet seviyesi')),
                ('order', models.IntegerField(default=0, help_text='Sıralama')),
                ('is_visible', models.BooleanField(default=True, help_text='Site üzerinde görünür mü?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cybersecurity Resource',
                'verbose_name_plural': 'Cybersecurity Resources',
                'ordering': ['-is_urgent', '-severity_level', 'type', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MusicPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Playlist adı', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Playlist açıklaması')),
                ('platform', models.CharField(choices=[('spotify', 'Spotify'), ('youtube', 'YouTube Music'), ('apple', 'Apple Music'), ('soundcloud', 'SoundCloud'), ('other', 'Diğer')], default='spotify', help_text='Müzik platformu', max_length=20)),
                ('url', models.URLField(help_text="Playlist URL'si")),
                ('embed_url', models.URLField(blank=True, help_text='Embed için URL (otomatik oluşturulur)')),
                ('cover_image', models.URLField(blank=True, help_text="Playlist kapak görseli URL'si")),
                ('track_count', models.IntegerField(default=0, help_text='Şarkı sayısı')),
                ('is_featured', models.BooleanField(default=False, help_text='Öne çıkan playlist olarak işaretle')),
                ('order', models.IntegerField(default=0, help_text='Sıralama')),
                ('is_visible', models.BooleanField(default=True, help_text='Site üzerinde görünür mü?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Music Playlist',
                'verbose_name_plural': 'Music Playlists',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique identifier for this information', max_length=100, unique=True)),
                ('value', models.TextField(help_text='The content/value of this information')),
                ('type', models.CharField(choices=[('text', 'Text'), ('json', 'JSON'), ('markdown', 'Markdown'), ('html', 'HTML')], default='text', help_text='How this content should be rendered', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this information is visible on the site')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personal Information',
                'verbose_name_plural': 'Personal Information',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SpotifyCurrentTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(help_text='Şarkı adı', max_length=200)),
                ('artist_name', models.CharField(help_text='Sanatçı adı', max_length=200)),
                ('album_name', models.CharField(blank=True, help_text='Albüm adı', max_length=200)),
                ('track_url', models.URLField(blank=True, help_text="Spotify şarkı URL'si")),
                ('image_url', models.URLField(blank=True, help_text="Albüm kapağı URL'si")),
                ('is_playing', models.BooleanField(default=False, help_text='Şu an çalıyor mu?')),
                ('progress_ms', models.IntegerField(default=0, help_text='Çalma ilerlemesi (milisaniye)')),
                ('duration_ms', models.IntegerField(default=0, help_text='Şarkı süresi (milisaniye)')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Son güncelleme')),
            ],
            options={
                'verbose_name': 'Spotify Current Track',
                'verbose_name_plural': 'Spotify Current Track',
                'get_latest_by': 'last_updated',
            },
        ),
        migrations.CreateModel(
            name='UsefulResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kaynak adı', max_length=100)),
                ('description', models.TextField(help_text='Kaynak açıklaması')),
                ('url', models.URLField(help_text="Kaynak URL'si")),
                ('type', models.CharField(choices=[('website', 'Website'), ('app', 'Uygulama'), ('tool', 'Araç'), ('extension', 'Tarayıcı Eklentisi'), ('other', 'Diğer')], default='website', help_text='Kaynak türü', max_length=20)),
                ('category', models.CharField(choices=[('development', 'Geliştirme'), ('design', 'Tasarım'), ('productivity', 'Verimlilik'), ('ai', 'Yapay Zeka'), ('learning', 'Öğrenme'), ('entertainment', 'Eğlence'), ('utility', 'Yardımcı Programlar'), ('other', 'Diğer')], default='utility', help_text='Kaynak kategorisi', max_length=20)),
                ('icon_url', models.URLField(blank=True, help_text="Kaynak ikonu URL'si", null=True)),
                ('image', models.ImageField(blank=True, help_text='Kaynak görseli', null=True, upload_to='useful_resources/')),
                ('is_free', models.BooleanField(default=True, help_text='Ücretsiz mi?')),
                ('is_featured', models.BooleanField(default=False, help_text='Öne çıkan kaynak olarak işaretle')),
                ('rating', models.FloatField(default=0.0, help_text='Kişisel değerlendirme (0-5)')),
                ('tags', models.CharField(blank=True, help_text='Virgülle ayrılmış etiketler', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Sıralama')),
                ('is_visible', models.BooleanField(default=True, help_text='Site üzerinde görünür mü?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Useful Resource',
                'verbose_name_plural': 'Useful Resources',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(help_text='Display name for the portfolio', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='admin_users', related_query_name='admin_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='admin_users', related_query_name='admin_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog yazısının başlığı', max_length=200)),
                ('slug', models.SlugField(help_text='URL için benzersiz slug (otomatik oluşturulur)', max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Kısa özet (300 karakter)', max_length=300)),
                ('content', models.TextField(help_text='Ana içerik (Markdown destekli)')),
                ('featured_image', models.ImageField(blank=True, help_text='Öne çıkan görsel', null=True, upload_to='blog_posts/')),
                ('tags', models.CharField(blank=True, help_text='Virgülle ayrılmış etiketler', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayınlandı'), ('archived', 'Arşivlendi')], default='draft', help_text='Yazı durumu', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Öne çıkan yazı olarak işaretle')),
                ('reading_time', models.IntegerField(default=0, help_text='Tahmini okuma süresi (dakika)')),
                ('view_count', models.IntegerField(default=0, help_text='Görüntülenme sayısı')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta açıklama', max_length=160)),
                ('published_at', models.DateTimeField(blank=True, help_text='Yayınlanma tarihi', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Yazı sahibi', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Blog yazısının kategorisi', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('website', 'Website'), ('other', 'Other')], help_text='Social media platform', max_length=50)),
                ('url', models.CharField(help_text='URL to your profile or email address', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of this social link', null=True)),
                ('stats', models.JSONField(blank=True, help_text='JSON data for follower counts, etc.', null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary/main social link')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this link is visible on the site')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order', 'platform'],
                'unique_together': {('platform', 'url')},
            },
        ),
    ]
